version: "3.0"
services:
  python-winrm:
    build: .
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: 'uvicorn main:app --reload --host 0.0.0.0 --port 8000'
    environment:
      - WINRM_HOST=${WINRM_HOST}
      - WINRM_USER=${WINRM_USER}
      - WINRM_PASSWORD=${WINRM_PASSWORD}
